version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tehran
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=yourUsername #optional
      - PASS=yourPassword #optional
    volumes:
      #     - path to data:/config
      - /var/www:/downloads
    #     - path to watch folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped



  serve:
    image: node:10-alpine
    restart: unless-stopped
    container_name: serve
    volumes:
      - /var/www:/downloads
    command: bash -c "npm i -g serve && serve -l 5000 /downloads"
    ports:
      - "9090:5000"
